const employees = [
  {
    id: "emp001",
    firstName: "Rahul",
    email: "employee1@gmail.com",
    password: "123",
    taskNumbers: {
      active: 1,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        id: 1,
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Design Login Page",
        taskDescription:
          "Create a responsive login page for the company website.",
        taskDate: "2026-08-24",
        category: "Frontend",
      },
      {
        id: 2,
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Fix Navbar Bug",
        taskDescription: "Fix the navigation menu issue on mobile screens.",
        taskDate: "2026-08-25",
        category: "Bug Fixing",
      },
      {
        id: 3,
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Create Contact Form",
        taskDescription:
          "Build a contact form with name, email and message fields.",
        taskDate: "2026-08-20",
        category: "Frontend",
      },
      {
        id: 4,
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Database Setup",
        taskDescription:
          "Set up the initial database structure for the project.",
        taskDate: "2026-08-18",
        category: "Backend",
      },
      {
        id: 5,
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "API Integration",
        taskDescription:
          "Integrate the employee API with the frontend application.",
        taskDate: "2026-08-26",
        category: "Backend",
      },
    ],
  },

  {
    id: "emp002",
    firstName: "Priya",
    email: "employee2@gmail.com",
    password: "123",
    taskNumbers: {
      active: 1,
      newTask: 2,
      completed: 2,
      failed: 0,
    },
    tasks: [
      {
        id: 6,
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Build Dashboard",
        taskDescription: "Create the main dashboard UI for the application.",
        taskDate: "2026-08-24",
        category: "Frontend",
      },
      {
        id: 7,
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Add Search Feature",
        taskDescription: "Implement search functionality for employee records.",
        taskDate: "2026-08-25",
        category: "Feature",
      },
      {
        id: 8,
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Create Employee Card",
        taskDescription: "Design reusable employee information cards.",
        taskDate: "2026-08-19",
        category: "UI Design",
      },
      {
        id: 9,
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Write Documentation",
        taskDescription: "Document the dashboard components and their usage.",
        taskDate: "2026-08-21",
        category: "Documentation",
      },
      {
        id: 10,
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Testing",
        taskDescription: "Test the dashboard and fix any UI issues.",
        taskDate: "2026-08-27",
        category: "Testing",
      },
    ],
  },

  {
    id: "emp003",
    firstName: "Arjun",
    email: "employee3@gmail.com",
    password: "123",
    taskNumbers: {
      active: 1,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        id: 11,
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Create REST API",
        taskDescription: "Develop REST API endpoints for employee management.",
        taskDate: "2026-08-24",
        category: "Backend",
      },
      {
        id: 12,
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Authentication",
        taskDescription: "Implement login and authentication functionality.",
        taskDate: "2026-08-26",
        category: "Backend",
      },
      {
        id: 13,
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Server Setup",
        taskDescription: "Configure the development server for the project.",
        taskDate: "2026-08-18",
        category: "Backend",
      },
      {
        id: 14,
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "API Testing",
        taskDescription: "Test all API endpoints using Postman.",
        taskDate: "2026-08-20",
        category: "Testing",
      },
      {
        id: 15,
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Database Integration",
        taskDescription: "Connect the backend application to the database.",
        taskDate: "2026-08-28",
        category: "Database",
      },
    ],
  },

  {
    id: "emp004",
    firstName: "Sneha",
    email: "employee4@gmail.com",
    password: "123",
    taskNumbers: {
      active: 1,
      newTask: 2,
      completed: 2,
      failed: 0,
    },
    tasks: [
      {
        id: 16,
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Design Homepage",
        taskDescription: "Create a modern and responsive homepage design.",
        taskDate: "2026-08-24",
        category: "Design",
      },
      {
        id: 17,
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Responsive Design",
        taskDescription:
          "Make the website responsive for mobile and tablet devices.",
        taskDate: "2026-08-25",
        category: "Frontend",
      },
      {
        id: 18,
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Color Theme",
        taskDescription: "Finalize the color palette for the website.",
        taskDate: "2026-08-19",
        category: "Design",
      },
      {
        id: 19,
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Create Components",
        taskDescription: "Create reusable UI components for the application.",
        taskDate: "2026-08-21",
        category: "React",
      },

      {
        id: 20,
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "UI Testing",
        taskDescription: "Test the UI across different screen sizes.",
        taskDate: "2026-08-27",
        category: "Testing",
      },
    ],
  },

  {
    id: "emp005",
    firstName: "Karan",
    email: "employee5@gmail.com",
    password: "123",
    taskNumbers: {
      active: 1,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        id: 21,
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Create Reports",
        taskDescription: "Create weekly performance reports for the team.",
        taskDate: "2026-08-24",
        category: "Reports",
      },
      {
        id: 22,
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Update Records",
        taskDescription: "Update employee records with the latest information.",
        taskDate: "2026-08-25",
        category: "Management",
      },
      {
        id: 23,
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Data Entry",
        taskDescription: "Enter the collected employee data into the system.",
        taskDate: "2026-08-19",
        category: "Data",
      },
      {
        id: 24,
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Monthly Report",
        taskDescription: "Prepare the monthly employee performance report.",
        taskDate: "2026-08-20",
        category: "Reports",
      },
      {
        id: 25,
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Team Meeting",
        taskDescription: "Attend the weekly team meeting and discuss progress.",
        taskDate: "2026-08-28",
        category: "Meeting",
      },
    ],
  },
];

const admin = [
  {
    id: "admin001",
    email: "admin@gmail.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  if (!localStorage.getItem("employees")) {
    localStorage.setItem("employees", JSON.stringify(employees));
  }

  if (!localStorage.getItem("admin")) {
    localStorage.setItem("admin", JSON.stringify(admin));
  }
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
